<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">

  <!-- parameters -->
  <xacro:property name="wheelbase" value="0.3302" />
  <xacro:property name="width" value="0.2032" />
  <xacro:property name="height" value="0.1" />
  <xacro:property name="ground_offset" value="0.04" />
  <xacro:property name="wheel_radius" value="0.0508" />
  <xacro:property name="wheel_length" value="0.0381" />

  <link name="base_link">
    <inertial>
      <mass value="1.5"/>
      <inertia ixx="0.02" iyy="0.02" izz="0.03" ixy="0" ixz="0" iyz="0"/>
    </inertial>

    <collision>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
    </visual>
  </link>

  <xacro:macro name="wheel" params="name">
    <link name="${name}">
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.001" iyy="0.001" izz="0.001"
                 ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <collision>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <visual>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </visual>
    </link>
  </xacro:macro>

  <xacro:wheel name="back_left_wheel"/>
  <xacro:wheel name="back_right_wheel"/>
  <xacro:wheel name="front_left_wheel"/>
  <xacro:wheel name="front_right_wheel"/>

  <joint name="back_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="back_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${-(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheelbase} ${(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheelbase} ${-(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

<gazebo>
  <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

    <ros>
      <namespace>/racecar</namespace>
    </ros>

    <leftJoint>front_left_joint</leftJoint>
    <leftJoint>back_left_joint</leftJoint>

    <rightJoint>front_right_joint</rightJoint>
    <rightJoint>back_right_joint</rightJoint>

    <wheelSeparation>${width}</wheelSeparation>
    <wheelDiameter>${2 * wheel_radius}</wheelDiameter>

    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_link</robotBaseFrame>

    <publishWheelTF>false</publishWheelTF>
    <publishOdomTF>true</publishOdomTF>
    <publishWheelJointState>true</publishWheelJointState>

    <updateRate>50</updateRate>
  </plugin>
</gazebo>



</robot>
